### ISSUE TITLE
[IMPROVEMENT] Wait to app launch and not process start

### ISSUE THREAD

**Issue by DeicPro** [DeicPro/magisk-manager-snapshot-updater#1]
Instead of waiting to process to start the script stuff, I think is better to wait to app launch by user action.

This is the part of script I say:
```
check(){
    echo "Waiting for Magisk Manager process start..."

    while sleep 1; do
        pid=$($bbx pgrep com.topjohnwu.magisk)
        error=$?
        if [ "$error" == 0 ]; then
            break
        fi
    done

    update
}
```

I'm thinking how to implement this improvement, but I'm a noob with this things... xD

A way to get this is grep expecifit ActivityManager of com.topjohnwu.magisk in logcat (USB debugging on needed) or with `am monitor`.

**Comment by stangri** [comment]
I'm not sure I can help you with the pgrep (is that what you're looking for?), but I'd do the loop like this:
```sh
    while :; do
        pid=$($bbx pgrep com.topjohnwu.magisk)
        [ "$?" -eq "0" ] && break || sleep 1
    done
```

**Comment by DeicPro** [comment]
The code I quote is already in service.sh, I want to replace it... for background install (`pm install`) it is nice (so Magisk Manager process is running when system is boot), but for gui install (`am start`) it is not and I want that when user launch Magisk Manager (is not nice that the package installer get open for surprise, is annoying, except if is open only when the focus is in Magisk Manager app).

IDK if I explained good ...

**Comment by stangri** [comment]
Oh, sorry, I don't know android well enough to help out.

I don't think sleeping until Magisk Manager is launched is a good idea tho. You can probably watch intents and listen to the launch of Magisk Manager, but I'd argue that if you can show the toast as soon as update is detected it's a better idea than to wait for user to launch Magisk Manager.

**Comment by DeicPro** [comment]
Is possible to show a toast from shell script? Interesting...

**Comment by DeicPro** [comment]
I find this app to show toast from shell script
https://forum.xda-developers.com/showpost.php?p=7995004&postcount=2

Works good... I only need to implement the intent stuff to run package installer when app is open.

**Comment by DeicPro** [comment]
Too found this:
https://github.com/halnovemila/Notify4Scripts

so interesting
